apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging
resources:
  - keycloak.yaml
  - ../../base/keycloak
patches:
  - target:
      kind: Certificate
      name: keycloak-internal-tls
    path: certificate-patch.yaml
