---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - bitnami-helm-repo.yaml
  - bitnami-helm-oci-repo.yaml
  - helm-release-blackbox-exporter.yaml
  - helm-release-kafka-exporter.yaml
  - helm-release-postgres-exporter.yaml
  - helm-release-prometheus.yaml
  - helm-release-thanos.yaml
  - karma.yaml
  - metrics-server-monitor.yaml
  - namespace.yaml
  - prometheus-community-helm-repo.yaml
